#!/usr/bin/env python3
"""Write public/_redirects and public/_headers — the two files the Cloudflare
Workers asset runtime reads. Both are generated because both need the route list.

_redirects carries only what the LIVE SITE itself redirects:

  /favicon.ico
      WordPress's Site Icon feature answers it with a 302 to the uploaded icon.
      Without a rule the port returns 404. Every page already declares
      <link rel="icon">, so this only covers the bare request.

  the no-trailing-slash form of every route
      `html_handling: auto-trailing-slash` already redirects /what-we-do to
      /what-we-do/, but it answers 307. The live site answers 301. The
      difference is not cosmetic at a migration: a 301 passes ranking signals
      to the slashed URL and a 307, being temporary, does not. _redirects is
      evaluated before asset routing, so these win.

_headers reproduces response headers the live site sends and Cloudflare does not:

  the four Sucuri security headers
      They come from the WAF in front of WordPress, a layer that does not exist
      here, so nothing in the ported markup reproduces them.

  max-age=86400 on /css/ and /js/
      Live sends it on every static asset. Cloudflare static assets default to
      `max-age=0, must-revalidate` for anything without a content hash in its
      name, which is both of these. /_astro/* is not listed: the adapter owns
      that rule and marks it immutable. /images/ is not listed either — under
      AD-9 the Worker serves no images, and img. sets its own cache headers.

  Content-Type: text/html; charset=UTF-8, per route
      Live sends the charset; the deployed Worker sends bare `text/html`. This
      needs one rule per route and cannot be done with a wildcard: _headers
      matches on the REQUEST path, and every page is requested as a directory
      (`/what-we-do/`), so `/*.html` matches only /404.html. `/*` would set the
      Content-Type of every image and stylesheet too. Hence the generated list.

The broader old-URL redirect set (/wp-content/uploads/*, /?p=N shortlinks, feeds,
date archives) is gate 14, wp-18-keep-old-links-working, published as Cloudflare
rules rather than from here.

Astro's own `redirects` config cannot express any of the redirects:
`trailingSlash: 'always'` rewrites every source to a slashed path, so
`/favicon.ico` becomes `/favicon.ico/` and `/what-we-do` becomes `/what-we-do/`,
matching itself. Files in public/ pass through the build untouched.
"""
import os as _os
_HERE = _os.path.dirname(_os.path.abspath(__file__))
_ROOT = _os.path.dirname(_HERE)
WORK = _os.environ.get('PORT_WORK') or _os.path.join(_ROOT, '.port-work')

import json, os

# Absolute, on the image host: under AD-9 the Worker serves no images at all, so there
# is no local path left to redirect to. _redirects accepts a full URL as a destination.
FAVICON = ('https://' + json.load(open(os.path.join(_ROOT, 'image-hosts.json')))['canonical']
           + '/2023/12/Rexdale-Mobile-Wash-Logo-Updated-23.webp')
GENERATED = '# GENERATED by tools/gen_edge.py — edit that, not this file.'

HEADERS_STATIC = """
# Live sends these four from Sucuri, the WAF in front of WordPress — not from
# WordPress — so nothing in the ported markup reproduces them and the port
# shipped with none of them. @astrojs/cloudflare prepends its own /_astro/*
# Cache-Control rule to this file at build time, so keep it to rules the adapter
# does not own.
#
#   x-frame-options: SAMEORIGIN
#   x-content-type-options: nosniff
#   x-xss-protection: 1; mode=block
#   content-security-policy: upgrade-insecure-requests;
#
# X-XSS-Protection is carried for parity only. Chrome removed the auditor it
# controls and the header does nothing there; it is still honoured by Safari.
/*
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  Content-Security-Policy: upgrade-insecure-requests;

# Yoast serves the sitemaps as text/xml and keeps them out of the index.
/*.xml
  Content-Type: text/xml; charset=UTF-8
  X-Robots-Tag: noindex, follow

# The live site sends `cache-control: max-age=86400` on every image, stylesheet
# and script. Without these the port revalidates all ~1MB of CSS on every page
# view — a regression no render comparison can see.
#
# No /images/* rule: under AD-9 the Worker serves no images. They come from
# img.rexdalemobilewash.ca, which answers with its own `cache-control:
# max-age=14400` and a `cf-cache-status`, and a rule here would never match.
/css/*
  Cache-Control: max-age=86400
/js/*
  Cache-Control: max-age=86400
"""


def main():
    meta = json.load(open(os.path.join(WORK, 'pages_meta.json')))
    urls = sorted(d['url'] for s, d in meta.items() if not s.startswith('_'))
    slashed = [u for u in urls if u != '/']

    red = [GENERATED, '#',
           '# Only the redirects the live WordPress site performs itself. The old-URL',
           '# redirect set is gate 14 (wp-18-keep-old-links-working), published as',
           '# Cloudflare rules.', '',
           '# WordPress answers /favicon.ico with a 302 to the Site Icon.',
           f'/favicon.ico  {FAVICON}  302', '',
           "# Trailing slash: the live site answers 301 here. Cloudflare's own",
           '# auto-trailing-slash handling answers 307, which passes no ranking signal.']
    red += [f'{u.rstrip("/")}  {u}  301' for u in slashed]
    open(os.path.join(_ROOT, 'public', '_redirects'), 'w', encoding='utf-8').write(
        '\n'.join(red) + '\n')
    print(f"  public/_redirects   1 favicon rule + {len(slashed)} trailing-slash rules")

    hdr = [GENERATED, HEADERS_STATIC.rstrip(), '',
           '# Live sends `content-type: text/html; charset=UTF-8`; the asset runtime',
           '# sends bare `text/html`. One rule per route: _headers matches the REQUEST',
           '# path, every page is requested as a directory, and `/*` would retype every',
           '# image and stylesheet too.']
    for u in urls + ['/404.html']:
        hdr += [u, '  Content-Type: text/html; charset=UTF-8']
    open(os.path.join(_ROOT, 'public', '_headers'), 'w', encoding='utf-8').write(
        '\n'.join(hdr) + '\n')
    print(f"  public/_headers     static rules + {len(urls) + 1} charset rules")


if __name__ == '__main__':
    main()
