#!/usr/bin/env python3
"""Write public/_redirects — the redirects the LIVE SITE itself performs.

Cloudflare Workers static assets read this file. Two things go in it:

  /favicon.ico
      WordPress's Site Icon feature answers it with a 302 to the uploaded icon.
      Without a rule the port returns 404. Every page already declares
      <link rel="icon">, so this only covers the bare request.

  the no-trailing-slash form of every route
      `html_handling: auto-trailing-slash` already redirects /what-we-do to
      /what-we-do/, but it answers 307. The live site answers 301. The
      difference is not cosmetic at a migration: a 301 passes ranking signals
      to the slashed URL and a 307, being temporary, does not. _redirects is
      evaluated before asset routing, so these win.

Astro's own `redirects` config cannot express either: `trailingSlash: 'always'`
rewrites every source to a slashed path, so `/favicon.ico` becomes
`/favicon.ico/` and `/what-we-do` becomes `/what-we-do/`, matching itself.

The broader old-URL redirect set (/wp-content/uploads/*, /?p=N shortlinks, feeds,
date archives) is gate 14, wp-18-keep-old-links-working, published as Cloudflare
rules rather than from here.
"""
import os as _os
_HERE = _os.path.dirname(_os.path.abspath(__file__))
_ROOT = _os.path.dirname(_HERE)
WORK = _os.environ.get('PORT_WORK') or _os.path.join(_ROOT, '.port-work')

import json, os

FAVICON = '/images/2023/12/Rexdale-Mobile-Wash-Logo-Updated-23.webp'


def main():
    meta = json.load(open(os.path.join(WORK, 'pages_meta.json')))
    urls = sorted(d['url'] for s, d in meta.items()
                  if not s.startswith('_') and d['url'] != '/')

    out = [
        '# GENERATED by tools/gen_redirects.py — edit that, not this file.',
        '#',
        '# Only the redirects the live WordPress site performs itself. The old-URL',
        '# redirect set is gate 14 (wp-18-keep-old-links-working), published as',
        '# Cloudflare rules.',
        '',
        '# WordPress answers /favicon.ico with a 302 to the Site Icon.',
        f'/favicon.ico  {FAVICON}  302',
        '',
        '# Trailing slash: the live site answers 301 here. Cloudflare\'s own',
        '# auto-trailing-slash handling answers 307, which passes no ranking signal.',
    ]
    for u in urls:
        out.append(f'{u.rstrip("/")}  {u}  301')
    open(os.path.join(_ROOT, 'public', '_redirects'), 'w', encoding='utf-8').write(
        '\n'.join(out) + '\n')
    print(f"  public/_redirects   1 favicon rule + {len(urls)} trailing-slash rules")


if __name__ == '__main__':
    main()
