#!/usr/bin/env bash
# Regenerate the ported pages from the captured live site.
#
# Everything under src/html/, src/nav-active.json and public/css/page-*.css is
# GENERATED by this script — edit the pipeline, not the output. The capture in
# tools/capture/ is the source of truth: the live WordPress site is switched off
# at gate 16, after which it cannot be re-fetched.
#
#   ./tools/run-port.sh          regenerate from the committed capture
#
set -euo pipefail
cd "$(dirname "$0")/.."
REPO="$PWD"
WORK="${PORT_WORK:-$REPO/.port-work}"
export PORT_WORK="$WORK" PORT_REPO="$REPO"

mkdir -p "$WORK"
if [ ! -d "$WORK/pages" ]; then
  echo "==> extracting captured live site"
  tar xzf tools/capture/live-capture-*.tar.gz -C "$WORK"
fi
cp -f tools/capture/css_map.json tools/capture/header_model.json \
      tools/capture/media_final.json tools/capture/header.neutral.html "$WORK/"
cp -f tools/header_apply.py "$WORK/" 2>/dev/null || true

echo "==> generating pages, per-page CSS and shared partials"
python3 tools/build_site.py
echo "==> generating .astro routes"
python3 tools/gen_pages.py
echo "==> generating 404"
python3 tools/gen_404.py
echo
echo "done. Now: npm run build"
